export function readFileContent(
  inputElement: HTMLInputElement,
  callback: (content: string | null) => void
): void {
  const file = inputElement.files?.[0];

  if (file) {
    const reader = new FileReader();

    reader.onload = function (event) {
      if (event.target) {
        const result = event.target.result as string;
        callback(result);
      }
    };

    reader.readAsText(file);
  } else {
    callback(null);
  }
}

export function getSymptomsByTail() {
  const symptoms = [
    { key: 'Modular Arithmetic', label: 'O algoritmo possui a característica' },
    {
      key: 'Matrix Multiplication',
      label: 'Uma das propriedades do algoritmo é',
    },
    { key: 'Exponentiation', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Large Exponents', label: 'O algoritmo tem a propriedade' },
    { key: 'Modular Division', label: 'Uma das propriedades do algoritmo é' },
    { key: 'GCD', label: 'Uma das propriedades do algoritmo é' },
    { key: 'LCM', label: 'O algoritmo possui a característica' },
    { key: 'Prime Numbers', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Fermat', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Miller-Rabin', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Binary Exponentiation', label: 'O algoritmo tem a propriedade' },
    { key: 'Relative Primes', label: 'O algoritmo tem a propriedade' },
    {
      key: 'Linear Diophantine Equation',
      label: 'O algoritmo tem a propriedade',
    },
    { key: 'Congruence', label: 'O algoritmo tem a propriedade' },
    {
      key: 'Extended Euclidian Algorithm',
      label: 'O seu algoritmo tem o sintoma',
    },
    { key: 'Coprime', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Modular Inverse', label: 'O algoritmo tem a propriedade' },
    {
      key: 'Modular Multiplicative Inverse',
      label: 'O seu algoritmo tem o sintoma',
    },
    { key: 'Divide and Conquer', label: 'O algoritmo possui a característica' },
    { key: 'Search', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Euclidian Algorithm', label: 'O algoritmo tem a propriedade' },
    { key: 'Diophantine Equation', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Integer Roots', label: 'O algoritmo possui a característica' },
    { key: 'Composite Numbers', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Divisible Numbers', label: 'O algoritmo tem a propriedade' },
    { key: 'Divisors', label: 'O seu algoritmo tem o sintoma' },
    {
      key: 'Chinese Remainder Theorem',
      label: 'O algoritmo tem a propriedade',
    },
    { key: 'Relatively Prime', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Modular Operation', label: 'O algoritmo tem a propriedade' },
    {
      key: 'Sieve of Erasthothenes',
      label: 'O algoritmo possui a característica',
    },
    { key: 'Binary', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Bitwise', label: 'O seu algoritmo tem o sintoma' },
    { key: "Two's complement", label: 'Uma das propriedades do algoritmo é' },
    { key: 'Shift', label: 'O algoritmo tem a propriedade' },
    { key: 'Power of Two', label: 'O seu algoritmo tem o sintoma' },
    { key: 'And', label: 'O algoritmo tem a propriedade' },
    { key: 'Or', label: 'O algoritmo possui a característica' },
    { key: 'Xor', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Bit', label: 'O algoritmo tem a propriedade' },
    {
      key: 'Multiply Polynomials',
      label: 'O algoritmo possui a característica',
    },
    { key: 'Coefficient Vector', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Scalar Product', label: 'O algoritmo tem a propriedade' },
    { key: 'String Matching', label: 'O algoritmo tem a propriedade' },
    { key: 'Data Structure', label: 'O algoritmo possui a característica' },
    { key: 'Stack', label: 'O algoritmo possui a característica' },
    { key: 'Queue', label: 'O algoritmo possui a característica' },
    { key: 'Array', label: 'O algoritmo possui a característica' },
    { key: 'Minimum Value', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Tree', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Combine Sets', label: 'O algoritmo tem a propriedade' },
    { key: 'Union-Find', label: 'O seu algoritmo tem o sintoma' },
    {
      key: 'Binary Indexed Tree',
      label: 'Uma das propriedades do algoritmo é',
    },
    { key: 'Sum of Values', label: 'O algoritmo tem a propriedade' },
    {
      key: 'Binary Associative Function',
      label: 'O algoritmo possui a característica',
    },
    { key: 'Bitwise Operations', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Minimum of Range', label: 'O algoritmo possui a característica' },
    { key: 'Minimal', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Maximal', label: 'O algoritmo possui a característica' },
    { key: 'Binary Tree', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Lazy Propagation', label: 'O seu algoritmo tem o sintoma' },
    {
      key: 'Dynamic Programming',
      label: 'O algoritmo possui a característica',
    },
    { key: 'Mininum Cost', label: 'O algoritmo tem a propriedade' },
    { key: 'Optimization', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Top-Down', label: 'O algoritmo possui a característica' },
    { key: 'Bottom-Up', label: 'Uma das propriedades do algoritmo é' },
    { key: 'BFS', label: 'O algoritmo possui a característica' },
    { key: 'DFS', label: 'O algoritmo possui a característica' },
    { key: 'String Comparing', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Modular Operations', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Probability', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Pattern Matching', label: 'Uma das propriedades do algoritmo é' },
    { key: 'String Searching', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Knuth-Morris-Pratt', label: 'Uma das propriedades do algoritmo é' },
    { key: 'KMP', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Preffix Function', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Longest Common Prefix', label: 'O algoritmo tem a propriedade' },
    { key: 'Graph', label: 'O algoritmo tem a propriedade' },
    { key: 'Automaton', label: 'O algoritmo possui a característica' },
    { key: 'Longest Common Substring', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Largest Common Substring', label: 'O algoritmo tem a propriedade' },
    { key: 'Permutations', label: 'O algoritmo possui a característica' },
    { key: 'Coefficients', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Combinatory', label: 'O algoritmo tem a propriedade' },
    { key: 'Factorial', label: 'O seu algoritmo tem o sintoma' },
    {
      key: 'Binomial Coefficients',
      label: 'Uma das propriedades do algoritmo é',
    },
    { key: 'Binary Search Tree', label: 'O algoritmo tem a propriedade' },
    { key: 'Binomial Coefficient', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Binary Search', label: 'O algoritmo tem a propriedade' },
    { key: 'Maximum Value', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Minimal Cost', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Geometry', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Line Equation', label: 'O algoritmo tem a propriedade' },
    { key: 'Normalization', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Vector', label: 'O algoritmo possui a característica' },
    {
      key: 'Two-Dimesional Plane',
      label: 'O algoritmo possui a característica',
    },
    { key: 'Equation System', label: 'O algoritmo possui a característica' },
    {
      key: 'Intersection Point of Lines',
      label: 'O seu algoritmo tem o sintoma',
    },
    { key: 'Radius of Circle', label: 'O algoritmo possui a característica' },
    { key: 'Center of Circle', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Vectors', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Circle-Line Intersection', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Convex Polygon', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Polar Distance', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Collinear', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Sets', label: 'O algoritmo tem a propriedade' },
    { key: 'Orientation', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Clockwise', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Counterclockwise', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Cyclic Shift', label: 'O algoritmo possui a característica' },
    { key: 'Convex Hull Trick', label: 'O algoritmo possui a característica' },
    { key: 'Segment Tree', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Polygons', label: 'O algoritmo possui a característica' },
    { key: 'Voronoi Diagram', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Deulanay Triangulation', label: 'O algoritmo tem a propriedade' },
    { key: 'Shortest Path', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Unweighted Graph', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Directed Graph', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Undirected Graph', label: 'O algoritmo possui a característica' },
    { key: 'Connected Components', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Width Search', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Depth First Search', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Connected Path', label: 'O seu algoritmo tem o sintoma' },
    { key: 'DSU', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Acyclic Graph', label: 'O algoritmo possui a característica' },
    { key: 'Subset', label: 'Uma das propriedades do algoritmo é' },
    {
      key: 'Undirected Weighted Graph',
      label: 'O algoritmo tem a propriedade',
    },
    {
      key: 'Single Source Shortest Path',
      label: 'Uma das propriedades do algoritmo é',
    },
    { key: 'Sparse Graph', label: 'O algoritmo tem a propriedade' },
    { key: 'Dense Graph', label: 'O algoritmo possui a característica' },
    {
      key: 'Undirected Unweighted Graph',
      label: 'Uma das propriedades do algoritmo é',
    },
    { key: 'Connected Graph', label: 'O algoritmo tem a propriedade' },
    { key: 'Kruskal', label: 'O algoritmo tem a propriedade' },
    { key: 'LCA', label: 'O algoritmo tem a propriedade' },
    { key: 'Negative Weight Edges', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Weighted Graph', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Minimum Spanning Tree', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Euler Tour', label: 'O algoritmo tem a propriedade' },
    { key: 'SQRT Decomposition', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Sparse Table', label: 'O algoritmo possui a característica' },
    {
      key: 'Connected Undirected Graph',
      label: 'O algoritmo possui a característica',
    },
    { key: 'Cycles', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Eulerian Cycle', label: 'O algoritmo tem a propriedade' },
    { key: 'Maximal Flow', label: 'O algoritmo tem a propriedade' },
    { key: 'Flow Network', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Maximum Flow', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Residual Capacity', label: 'O algoritmo tem a propriedade' },
    { key: 'Residual Network', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Max-Flow Min-Cut', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Bellman-Ford', label: 'O algoritmo possui a característica' },
    { key: 'Dijkstra', label: 'O algoritmo tem a propriedade' },
    { key: 'Dinic', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Bipartite Graph', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Maximum Match', label: 'O algoritmo tem a propriedade' },
    { key: 'Permutation', label: 'O algoritmo possui a característica' },
    { key: 'Binary Lifting', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Fenwick Tree', label: 'O algoritmo tem a propriedade' },
    { key: 'Nim', label: 'Uma das propriedades do algoritmo é' },
    { key: 'Game Theory', label: 'O algoritmo tem a propriedade' },
    { key: 'Perfect Information', label: 'O algoritmo tem a propriedade' },
    { key: 'Finite Game', label: 'O seu algoritmo tem o sintoma' },
    { key: 'Xor-Sum', label: 'O algoritmo tem a propriedade' },
    { key: 'Bitwise Operation', label: 'O algoritmo possui a característica' },
  ];
  return symptoms;
}
